name: "Setup Gradle"
description: Setup Java and Gradle environment
inputs:
  java-version:  
    required: false
    default: 21
  java-distro:
    required: false
    default: 'liberica'
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@main
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distro }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main
    - name: Prepare ./gradlew
      uses: gradle build
    
