name: "Setup Gradle"

branding:
  icon: 'package'
  color: 'red'
description: Setup Java and Gradle environment
inputs:
  java-version:
    required: false
    description: https://github.com/actions/setup-java?tab=readme-ov-file#supported-version-syntax
    default: '21'
  java-distro:
    required: false
    description: https://github.com/actions/setup-java?tab=readme-ov-file#supported-distributions
    default: 'liberica'
runs:
  using: "composite"
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@main
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.java-distro }}
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@main
    - shell: bash
      run: gradle init
    - shell: bash
      run: gradle build

